{{- if not .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hydro-habitat.fullname" . }}
  labels:
    {{- include "hydro-habitat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hydro-habitat.selectorLabels" . | nindent 4 }}
{{- end }}
